# Logger Config
logging:
  config: classpath:logback.xml
  level:
    com.baomidou.mybatisplus.samples: debug
    org.springframework.cloud: info

spring:
  banner:
    location: classpath:banner-pro.txt
  application:
    name: itcc-asr
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  #test
  thymeleaf:
    cache: false # 关闭页面缓存
    encoding: UTF-8 # 模板编码
    prefix: classpath:/templates/ # 页面映射路径
    suffix: .html # 试图后的后缀
#test

http:
  port: 52220


server:
  port: 52118
  ssl:
    protocol: TLS
    key-store: classpath:javastack.keystore
    key-store-password: 123456
    key-store-type: JKS
    key-alias: tomcat
    key-password: 123456
#keytool -genkeypair -alias tomcat -keyalg RSA -keystore D:\javastack.keystore
#keytool -export -alias tomcat -keystore D:\javastack.keystore -storepass 123456 -file D:\javastack.crt
file:
  upload:
    #path: /home/asrdata/
    path: D:\data\asrdata\

asr: 1
url: http://172.16.12.39:10011/createRec