// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tts.proto

package com.iflytek.vcp.voice.engine.tts.core;

public final class TtsOuterClass {
    private TtsOuterClass() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface TtsRequestOrBuilder extends
            // @@protoc_insertion_point(interface_extends:tts.TtsRequest)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * 创建会话参数
         * </pre>
         *
         * <code>map&lt;string, string&gt; sessionParam = 1;</code>
         */
        int getSessionParamCount();

        /**
         * <pre>
         * 创建会话参数
         * </pre>
         *
         * <code>map&lt;string, string&gt; sessionParam = 1;</code>
         */
        boolean containsSessionParam(
                String key);

        /**
         * Use {@link #getSessionParamMap()} instead.
         */
        @Deprecated
        java.util.Map<String, String>
        getSessionParam();

        /**
         * <pre>
         * 创建会话参数
         * </pre>
         *
         * <code>map&lt;string, string&gt; sessionParam = 1;</code>
         */
        java.util.Map<String, String>
        getSessionParamMap();

        /**
         * <pre>
         * 创建会话参数
         * </pre>
         *
         * <code>map&lt;string, string&gt; sessionParam = 1;</code>
         */

        String getSessionParamOrDefault(
                String key,
                String defaultValue);

        /**
         * <pre>
         * 创建会话参数
         * </pre>
         *
         * <code>map&lt;string, string&gt; sessionParam = 1;</code>
         */

        String getSessionParamOrThrow(
                String key);

        /**
         * <pre>
         * 需要tts合成的文本数据
         * </pre>
         *
         * <code>string text = 2;</code>
         */
        String getText();

        /**
         * <pre>
         * 需要tts合成的文本数据
         * </pre>
         *
         * <code>string text = 2;</code>
         */
        com.google.protobuf.ByteString
        getTextBytes();

        /**
         * <pre>
         * 最后一次文本标志符
         * </pre>
         *
         * <code>bool endFlag = 3;</code>
         */
        boolean getEndFlag();
    }

    /**
     * <pre>
     * 请求参数
     * </pre>
     * <p>
     * Protobuf type {@code tts.TtsRequest}
     */
    public static final class TtsRequest extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:tts.TtsRequest)
            TtsRequestOrBuilder {
        // Use TtsRequest.newBuilder() to construct.
        private TtsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private TtsRequest() {
            text_ = "";
            endFlag_ = false;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private TtsRequest(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                                sessionParam_ = com.google.protobuf.MapField.newMapField(
                                        SessionParamDefaultEntryHolder.defaultEntry);
                                mutable_bitField0_ |= 0x00000001;
                            }
                            com.google.protobuf.MapEntry<String, String>
                                    sessionParam__ = input.readMessage(
                                    SessionParamDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                            sessionParam_.getMutableMap().put(
                                    sessionParam__.getKey(), sessionParam__.getValue());
                            break;
                        }
                        case 18: {
                            String s = input.readStringRequireUtf8();

                            text_ = s;
                            break;
                        }
                        case 24: {

                            endFlag_ = input.readBool();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return TtsOuterClass.internal_static_tts_TtsRequest_descriptor;
        }

        @SuppressWarnings({"rawtypes"})
        protected com.google.protobuf.MapField internalGetMapField(
                int number) {
            switch (number) {
                case 1:
                    return internalGetSessionParam();
                default:
                    throw new RuntimeException(
                            "Invalid map field number: " + number);
            }
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return TtsOuterClass.internal_static_tts_TtsRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            TtsRequest.class, Builder.class);
        }

        private int bitField0_;
        public static final int SESSIONPARAM_FIELD_NUMBER = 1;

        private static final class SessionParamDefaultEntryHolder {
            static final com.google.protobuf.MapEntry<
                    String, String> defaultEntry =
                    com.google.protobuf.MapEntry
                            .<String, String>newDefaultInstance(
                                    TtsOuterClass.internal_static_tts_TtsRequest_SessionParamEntry_descriptor,
                                    com.google.protobuf.WireFormat.FieldType.STRING,
                                    "",
                                    com.google.protobuf.WireFormat.FieldType.STRING,
                                    "");
        }

        private com.google.protobuf.MapField<
                String, String> sessionParam_;

        private com.google.protobuf.MapField<String, String>
        internalGetSessionParam() {
            if (sessionParam_ == null) {
                return com.google.protobuf.MapField.emptyMapField(
                        SessionParamDefaultEntryHolder.defaultEntry);
            }
            return sessionParam_;
        }

        public int getSessionParamCount() {
            return internalGetSessionParam().getMap().size();
        }

        /**
         * <pre>
         * 创建会话参数
         * </pre>
         *
         * <code>map&lt;string, string&gt; sessionParam = 1;</code>
         */

        public boolean containsSessionParam(
                String key) {
            if (key == null) {
                throw new NullPointerException();
            }
            return internalGetSessionParam().getMap().containsKey(key);
        }

        /**
         * Use {@link #getSessionParamMap()} instead.
         */
        @Deprecated
        public java.util.Map<String, String> getSessionParam() {
            return getSessionParamMap();
        }

        /**
         * <pre>
         * 创建会话参数
         * </pre>
         *
         * <code>map&lt;string, string&gt; sessionParam = 1;</code>
         */

        public java.util.Map<String, String> getSessionParamMap() {
            return internalGetSessionParam().getMap();
        }

        /**
         * <pre>
         * 创建会话参数
         * </pre>
         *
         * <code>map&lt;string, string&gt; sessionParam = 1;</code>
         */

        public String getSessionParamOrDefault(
                String key,
                String defaultValue) {
            if (key == null) {
                throw new NullPointerException();
            }
            java.util.Map<String, String> map =
                    internalGetSessionParam().getMap();
            return map.containsKey(key) ? map.get(key) : defaultValue;
        }

        /**
         * <pre>
         * 创建会话参数
         * </pre>
         *
         * <code>map&lt;string, string&gt; sessionParam = 1;</code>
         */

        public String getSessionParamOrThrow(
                String key) {
            if (key == null) {
                throw new NullPointerException();
            }
            java.util.Map<String, String> map =
                    internalGetSessionParam().getMap();
            if (!map.containsKey(key)) {
                throw new IllegalArgumentException();
            }
            return map.get(key);
        }

        public static final int TEXT_FIELD_NUMBER = 2;
        private volatile Object text_;

        /**
         * <pre>
         * 需要tts合成的文本数据
         * </pre>
         *
         * <code>string text = 2;</code>
         */
        public String getText() {
            Object ref = text_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                text_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 需要tts合成的文本数据
         * </pre>
         *
         * <code>string text = 2;</code>
         */
        public com.google.protobuf.ByteString
        getTextBytes() {
            Object ref = text_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                text_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int ENDFLAG_FIELD_NUMBER = 3;
        private boolean endFlag_;

        /**
         * <pre>
         * 最后一次文本标志符
         * </pre>
         *
         * <code>bool endFlag = 3;</code>
         */
        public boolean getEndFlag() {
            return endFlag_;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            com.google.protobuf.GeneratedMessageV3
                    .serializeStringMapTo(
                            output,
                            internalGetSessionParam(),
                            SessionParamDefaultEntryHolder.defaultEntry,
                            1);
            if (!getTextBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, text_);
            }
            if (endFlag_ != false) {
                output.writeBool(3, endFlag_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            for (java.util.Map.Entry<String, String> entry
                    : internalGetSessionParam().getMap().entrySet()) {
                com.google.protobuf.MapEntry<String, String>
                        sessionParam__ = SessionParamDefaultEntryHolder.defaultEntry.newBuilderForType()
                        .setKey(entry.getKey())
                        .setValue(entry.getValue())
                        .build();
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, sessionParam__);
            }
            if (!getTextBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, text_);
            }
            if (endFlag_ != false) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(3, endFlag_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof TtsRequest)) {
                return super.equals(obj);
            }
            TtsRequest other = (TtsRequest) obj;

            boolean result = true;
            result = result && internalGetSessionParam().equals(
                    other.internalGetSessionParam());
            result = result && getText()
                    .equals(other.getText());
            result = result && (getEndFlag()
                    == other.getEndFlag());
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (!internalGetSessionParam().getMap().isEmpty()) {
                hash = (37 * hash) + SESSIONPARAM_FIELD_NUMBER;
                hash = (53 * hash) + internalGetSessionParam().hashCode();
            }
            hash = (37 * hash) + TEXT_FIELD_NUMBER;
            hash = (53 * hash) + getText().hashCode();
            hash = (37 * hash) + ENDFLAG_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                    getEndFlag());
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static TtsRequest parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static TtsRequest parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TtsRequest parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static TtsRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TtsRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static TtsRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TtsRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static TtsRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static TtsRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static TtsRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static TtsRequest parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static TtsRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(TtsRequest prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * <pre>
         * 请求参数
         * </pre>
         * <p>
         * Protobuf type {@code tts.TtsRequest}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:tts.TtsRequest)
                TtsRequestOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return TtsOuterClass.internal_static_tts_TtsRequest_descriptor;
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMapField(
                    int number) {
                switch (number) {
                    case 1:
                        return internalGetSessionParam();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMutableMapField(
                    int number) {
                switch (number) {
                    case 1:
                        return internalGetMutableSessionParam();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return TtsOuterClass.internal_static_tts_TtsRequest_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                TtsRequest.class, Builder.class);
            }

            // Construct using com.iflytek.tts.sdk.core.TtsOuterClass.TtsRequest.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                internalGetMutableSessionParam().clear();
                text_ = "";

                endFlag_ = false;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return TtsOuterClass.internal_static_tts_TtsRequest_descriptor;
            }

            public TtsRequest getDefaultInstanceForType() {
                return TtsRequest.getDefaultInstance();
            }

            public TtsRequest build() {
                TtsRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public TtsRequest buildPartial() {
                TtsRequest result = new TtsRequest(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                result.sessionParam_ = internalGetSessionParam();
                result.sessionParam_.makeImmutable();
                result.text_ = text_;
                result.endFlag_ = endFlag_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof TtsRequest) {
                    return mergeFrom((TtsRequest) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(TtsRequest other) {
                if (other == TtsRequest.getDefaultInstance()) return this;
                internalGetMutableSessionParam().mergeFrom(
                        other.internalGetSessionParam());
                if (!other.getText().isEmpty()) {
                    text_ = other.text_;
                    onChanged();
                }
                if (other.getEndFlag() != false) {
                    setEndFlag(other.getEndFlag());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                TtsRequest parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (TtsRequest) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private com.google.protobuf.MapField<
                    String, String> sessionParam_;

            private com.google.protobuf.MapField<String, String>
            internalGetSessionParam() {
                if (sessionParam_ == null) {
                    return com.google.protobuf.MapField.emptyMapField(
                            SessionParamDefaultEntryHolder.defaultEntry);
                }
                return sessionParam_;
            }

            private com.google.protobuf.MapField<String, String>
            internalGetMutableSessionParam() {
                onChanged();
                ;
                if (sessionParam_ == null) {
                    sessionParam_ = com.google.protobuf.MapField.newMapField(
                            SessionParamDefaultEntryHolder.defaultEntry);
                }
                if (!sessionParam_.isMutable()) {
                    sessionParam_ = sessionParam_.copy();
                }
                return sessionParam_;
            }

            public int getSessionParamCount() {
                return internalGetSessionParam().getMap().size();
            }

            /**
             * <pre>
             * 创建会话参数
             * </pre>
             *
             * <code>map&lt;string, string&gt; sessionParam = 1;</code>
             */

            public boolean containsSessionParam(
                    String key) {
                if (key == null) {
                    throw new NullPointerException();
                }
                return internalGetSessionParam().getMap().containsKey(key);
            }

            /**
             * Use {@link #getSessionParamMap()} instead.
             */
            @Deprecated
            public java.util.Map<String, String> getSessionParam() {
                return getSessionParamMap();
            }

            /**
             * <pre>
             * 创建会话参数
             * </pre>
             *
             * <code>map&lt;string, string&gt; sessionParam = 1;</code>
             */

            public java.util.Map<String, String> getSessionParamMap() {
                return internalGetSessionParam().getMap();
            }

            /**
             * <pre>
             * 创建会话参数
             * </pre>
             *
             * <code>map&lt;string, string&gt; sessionParam = 1;</code>
             */

            public String getSessionParamOrDefault(
                    String key,
                    String defaultValue) {
                if (key == null) {
                    throw new NullPointerException();
                }
                java.util.Map<String, String> map =
                        internalGetSessionParam().getMap();
                return map.containsKey(key) ? map.get(key) : defaultValue;
            }

            /**
             * <pre>
             * 创建会话参数
             * </pre>
             *
             * <code>map&lt;string, string&gt; sessionParam = 1;</code>
             */

            public String getSessionParamOrThrow(
                    String key) {
                if (key == null) {
                    throw new NullPointerException();
                }
                java.util.Map<String, String> map =
                        internalGetSessionParam().getMap();
                if (!map.containsKey(key)) {
                    throw new IllegalArgumentException();
                }
                return map.get(key);
            }

            public Builder clearSessionParam() {
                internalGetMutableSessionParam().getMutableMap()
                        .clear();
                return this;
            }

            /**
             * <pre>
             * 创建会话参数
             * </pre>
             *
             * <code>map&lt;string, string&gt; sessionParam = 1;</code>
             */

            public Builder removeSessionParam(
                    String key) {
                if (key == null) {
                    throw new NullPointerException();
                }
                internalGetMutableSessionParam().getMutableMap()
                        .remove(key);
                return this;
            }

            /**
             * Use alternate mutation accessors instead.
             */
            @Deprecated
            public java.util.Map<String, String>
            getMutableSessionParam() {
                return internalGetMutableSessionParam().getMutableMap();
            }

            /**
             * <pre>
             * 创建会话参数
             * </pre>
             *
             * <code>map&lt;string, string&gt; sessionParam = 1;</code>
             */
            public Builder putSessionParam(
                    String key,
                    String value) {
                if (key == null) {
                    throw new NullPointerException();
                }
                if (value == null) {
                    throw new NullPointerException();
                }
                internalGetMutableSessionParam().getMutableMap()
                        .put(key, value);
                return this;
            }

            /**
             * <pre>
             * 创建会话参数
             * </pre>
             *
             * <code>map&lt;string, string&gt; sessionParam = 1;</code>
             */

            public Builder putAllSessionParam(
                    java.util.Map<String, String> values) {
                internalGetMutableSessionParam().getMutableMap()
                        .putAll(values);
                return this;
            }

            private Object text_ = "";

            /**
             * <pre>
             * 需要tts合成的文本数据
             * </pre>
             *
             * <code>string text = 2;</code>
             */
            public String getText() {
                Object ref = text_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    text_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <pre>
             * 需要tts合成的文本数据
             * </pre>
             *
             * <code>string text = 2;</code>
             */
            public com.google.protobuf.ByteString
            getTextBytes() {
                Object ref = text_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    text_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 需要tts合成的文本数据
             * </pre>
             *
             * <code>string text = 2;</code>
             */
            public Builder setText(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                text_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 需要tts合成的文本数据
             * </pre>
             *
             * <code>string text = 2;</code>
             */
            public Builder clearText() {

                text_ = getDefaultInstance().getText();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 需要tts合成的文本数据
             * </pre>
             *
             * <code>string text = 2;</code>
             */
            public Builder setTextBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                text_ = value;
                onChanged();
                return this;
            }

            private boolean endFlag_;

            /**
             * <pre>
             * 最后一次文本标志符
             * </pre>
             *
             * <code>bool endFlag = 3;</code>
             */
            public boolean getEndFlag() {
                return endFlag_;
            }

            /**
             * <pre>
             * 最后一次文本标志符
             * </pre>
             *
             * <code>bool endFlag = 3;</code>
             */
            public Builder setEndFlag(boolean value) {

                endFlag_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 最后一次文本标志符
             * </pre>
             *
             * <code>bool endFlag = 3;</code>
             */
            public Builder clearEndFlag() {

                endFlag_ = false;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:tts.TtsRequest)
        }

        // @@protoc_insertion_point(class_scope:tts.TtsRequest)
        private static final TtsRequest DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new TtsRequest();
        }

        public static TtsRequest getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<TtsRequest>
                PARSER = new com.google.protobuf.AbstractParser<TtsRequest>() {
            public TtsRequest parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new TtsRequest(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<TtsRequest> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<TtsRequest> getParserForType() {
            return PARSER;
        }

        public TtsRequest getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface TtsResultOrBuilder extends
            // @@protoc_insertion_point(interface_extends:tts.TtsResult)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * 错误描述
         * </pre>
         *
         * <code>string errStr = 1;</code>
         */
        String getErrStr();

        /**
         * <pre>
         * 错误描述
         * </pre>
         *
         * <code>string errStr = 1;</code>
         */
        com.google.protobuf.ByteString
        getErrStrBytes();

        /**
         * <pre>
         * 错误码
         * </pre>
         *
         * <code>int32 errCode = 2;</code>
         */
        int getErrCode();

        /**
         * <pre>
         * 返回的音频数据（没有音频头）
         * </pre>
         *
         * <code>bytes data = 3;</code>
         */
        com.google.protobuf.ByteString getData();

        /**
         * <pre>
         * 音频数据的信息
         * </pre>
         *
         * <code>map&lt;string, string&gt; dataInfo = 4;</code>
         */
        int getDataInfoCount();

        /**
         * <pre>
         * 音频数据的信息
         * </pre>
         *
         * <code>map&lt;string, string&gt; dataInfo = 4;</code>
         */
        boolean containsDataInfo(
                String key);

        /**
         * Use {@link #getDataInfoMap()} instead.
         */
        @Deprecated
        java.util.Map<String, String>
        getDataInfo();

        /**
         * <pre>
         * 音频数据的信息
         * </pre>
         *
         * <code>map&lt;string, string&gt; dataInfo = 4;</code>
         */
        java.util.Map<String, String>
        getDataInfoMap();

        /**
         * <pre>
         * 音频数据的信息
         * </pre>
         *
         * <code>map&lt;string, string&gt; dataInfo = 4;</code>
         */

        String getDataInfoOrDefault(
                String key,
                String defaultValue);

        /**
         * <pre>
         * 音频数据的信息
         * </pre>
         *
         * <code>map&lt;string, string&gt; dataInfo = 4;</code>
         */

        String getDataInfoOrThrow(
                String key);

        /**
         * <pre>
         * 最后一次音频标识符
         * </pre>
         *
         * <code>bool endFlag = 5;</code>
         */
        boolean getEndFlag();
    }

    /**
     * <pre>
     * 返回结果
     * </pre>
     * <p>
     * Protobuf type {@code tts.TtsResult}
     */
    public static final class TtsResult extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:tts.TtsResult)
            TtsResultOrBuilder {
        // Use TtsResult.newBuilder() to construct.
        private TtsResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private TtsResult() {
            errStr_ = "";
            errCode_ = 0;
            data_ = com.google.protobuf.ByteString.EMPTY;
            endFlag_ = false;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private TtsResult(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            String s = input.readStringRequireUtf8();

                            errStr_ = s;
                            break;
                        }
                        case 16: {

                            errCode_ = input.readInt32();
                            break;
                        }
                        case 26: {

                            data_ = input.readBytes();
                            break;
                        }
                        case 34: {
                            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                                dataInfo_ = com.google.protobuf.MapField.newMapField(
                                        DataInfoDefaultEntryHolder.defaultEntry);
                                mutable_bitField0_ |= 0x00000008;
                            }
                            com.google.protobuf.MapEntry<String, String>
                                    dataInfo__ = input.readMessage(
                                    DataInfoDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                            dataInfo_.getMutableMap().put(
                                    dataInfo__.getKey(), dataInfo__.getValue());
                            break;
                        }
                        case 40: {

                            endFlag_ = input.readBool();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return TtsOuterClass.internal_static_tts_TtsResult_descriptor;
        }

        @SuppressWarnings({"rawtypes"})
        protected com.google.protobuf.MapField internalGetMapField(
                int number) {
            switch (number) {
                case 4:
                    return internalGetDataInfo();
                default:
                    throw new RuntimeException(
                            "Invalid map field number: " + number);
            }
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return TtsOuterClass.internal_static_tts_TtsResult_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            TtsResult.class, Builder.class);
        }

        private int bitField0_;
        public static final int ERRSTR_FIELD_NUMBER = 1;
        private volatile Object errStr_;

        /**
         * <pre>
         * 错误描述
         * </pre>
         *
         * <code>string errStr = 1;</code>
         */
        public String getErrStr() {
            Object ref = errStr_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                errStr_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 错误描述
         * </pre>
         *
         * <code>string errStr = 1;</code>
         */
        public com.google.protobuf.ByteString
        getErrStrBytes() {
            Object ref = errStr_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                errStr_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int ERRCODE_FIELD_NUMBER = 2;
        private int errCode_;

        /**
         * <pre>
         * 错误码
         * </pre>
         *
         * <code>int32 errCode = 2;</code>
         */
        public int getErrCode() {
            return errCode_;
        }

        public static final int DATA_FIELD_NUMBER = 3;
        private com.google.protobuf.ByteString data_;

        /**
         * <pre>
         * 返回的音频数据（没有音频头）
         * </pre>
         *
         * <code>bytes data = 3;</code>
         */
        public com.google.protobuf.ByteString getData() {
            return data_;
        }

        public static final int DATAINFO_FIELD_NUMBER = 4;

        private static final class DataInfoDefaultEntryHolder {
            static final com.google.protobuf.MapEntry<
                    String, String> defaultEntry =
                    com.google.protobuf.MapEntry
                            .<String, String>newDefaultInstance(
                                    TtsOuterClass.internal_static_tts_TtsResult_DataInfoEntry_descriptor,
                                    com.google.protobuf.WireFormat.FieldType.STRING,
                                    "",
                                    com.google.protobuf.WireFormat.FieldType.STRING,
                                    "");
        }

        private com.google.protobuf.MapField<
                String, String> dataInfo_;

        private com.google.protobuf.MapField<String, String>
        internalGetDataInfo() {
            if (dataInfo_ == null) {
                return com.google.protobuf.MapField.emptyMapField(
                        DataInfoDefaultEntryHolder.defaultEntry);
            }
            return dataInfo_;
        }

        public int getDataInfoCount() {
            return internalGetDataInfo().getMap().size();
        }

        /**
         * <pre>
         * 音频数据的信息
         * </pre>
         *
         * <code>map&lt;string, string&gt; dataInfo = 4;</code>
         */

        public boolean containsDataInfo(
                String key) {
            if (key == null) {
                throw new NullPointerException();
            }
            return internalGetDataInfo().getMap().containsKey(key);
        }

        /**
         * Use {@link #getDataInfoMap()} instead.
         */
        @Deprecated
        public java.util.Map<String, String> getDataInfo() {
            return getDataInfoMap();
        }

        /**
         * <pre>
         * 音频数据的信息
         * </pre>
         *
         * <code>map&lt;string, string&gt; dataInfo = 4;</code>
         */

        public java.util.Map<String, String> getDataInfoMap() {
            return internalGetDataInfo().getMap();
        }

        /**
         * <pre>
         * 音频数据的信息
         * </pre>
         *
         * <code>map&lt;string, string&gt; dataInfo = 4;</code>
         */

        public String getDataInfoOrDefault(
                String key,
                String defaultValue) {
            if (key == null) {
                throw new NullPointerException();
            }
            java.util.Map<String, String> map =
                    internalGetDataInfo().getMap();
            return map.containsKey(key) ? map.get(key) : defaultValue;
        }

        /**
         * <pre>
         * 音频数据的信息
         * </pre>
         *
         * <code>map&lt;string, string&gt; dataInfo = 4;</code>
         */

        public String getDataInfoOrThrow(
                String key) {
            if (key == null) {
                throw new NullPointerException();
            }
            java.util.Map<String, String> map =
                    internalGetDataInfo().getMap();
            if (!map.containsKey(key)) {
                throw new IllegalArgumentException();
            }
            return map.get(key);
        }

        public static final int ENDFLAG_FIELD_NUMBER = 5;
        private boolean endFlag_;

        /**
         * <pre>
         * 最后一次音频标识符
         * </pre>
         *
         * <code>bool endFlag = 5;</code>
         */
        public boolean getEndFlag() {
            return endFlag_;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getErrStrBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, errStr_);
            }
            if (errCode_ != 0) {
                output.writeInt32(2, errCode_);
            }
            if (!data_.isEmpty()) {
                output.writeBytes(3, data_);
            }
            com.google.protobuf.GeneratedMessageV3
                    .serializeStringMapTo(
                            output,
                            internalGetDataInfo(),
                            DataInfoDefaultEntryHolder.defaultEntry,
                            4);
            if (endFlag_ != false) {
                output.writeBool(5, endFlag_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getErrStrBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, errStr_);
            }
            if (errCode_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, errCode_);
            }
            if (!data_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(3, data_);
            }
            for (java.util.Map.Entry<String, String> entry
                    : internalGetDataInfo().getMap().entrySet()) {
                com.google.protobuf.MapEntry<String, String>
                        dataInfo__ = DataInfoDefaultEntryHolder.defaultEntry.newBuilderForType()
                        .setKey(entry.getKey())
                        .setValue(entry.getValue())
                        .build();
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(4, dataInfo__);
            }
            if (endFlag_ != false) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(5, endFlag_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof TtsResult)) {
                return super.equals(obj);
            }
            TtsResult other = (TtsResult) obj;

            boolean result = true;
            result = result && getErrStr()
                    .equals(other.getErrStr());
            result = result && (getErrCode()
                    == other.getErrCode());
            result = result && getData()
                    .equals(other.getData());
            result = result && internalGetDataInfo().equals(
                    other.internalGetDataInfo());
            result = result && (getEndFlag()
                    == other.getEndFlag());
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + ERRSTR_FIELD_NUMBER;
            hash = (53 * hash) + getErrStr().hashCode();
            hash = (37 * hash) + ERRCODE_FIELD_NUMBER;
            hash = (53 * hash) + getErrCode();
            hash = (37 * hash) + DATA_FIELD_NUMBER;
            hash = (53 * hash) + getData().hashCode();
            if (!internalGetDataInfo().getMap().isEmpty()) {
                hash = (37 * hash) + DATAINFO_FIELD_NUMBER;
                hash = (53 * hash) + internalGetDataInfo().hashCode();
            }
            hash = (37 * hash) + ENDFLAG_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                    getEndFlag());
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static TtsResult parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static TtsResult parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TtsResult parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static TtsResult parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TtsResult parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static TtsResult parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TtsResult parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static TtsResult parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static TtsResult parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static TtsResult parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static TtsResult parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static TtsResult parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(TtsResult prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * <pre>
         * 返回结果
         * </pre>
         * <p>
         * Protobuf type {@code tts.TtsResult}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:tts.TtsResult)
                TtsResultOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return TtsOuterClass.internal_static_tts_TtsResult_descriptor;
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMapField(
                    int number) {
                switch (number) {
                    case 4:
                        return internalGetDataInfo();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMutableMapField(
                    int number) {
                switch (number) {
                    case 4:
                        return internalGetMutableDataInfo();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return TtsOuterClass.internal_static_tts_TtsResult_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                TtsResult.class, Builder.class);
            }

            // Construct using com.iflytek.tts.sdk.core.TtsOuterClass.TtsResult.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                errStr_ = "";

                errCode_ = 0;

                data_ = com.google.protobuf.ByteString.EMPTY;

                internalGetMutableDataInfo().clear();
                endFlag_ = false;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return TtsOuterClass.internal_static_tts_TtsResult_descriptor;
            }

            public TtsResult getDefaultInstanceForType() {
                return TtsResult.getDefaultInstance();
            }

            public TtsResult build() {
                TtsResult result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public TtsResult buildPartial() {
                TtsResult result = new TtsResult(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                result.errStr_ = errStr_;
                result.errCode_ = errCode_;
                result.data_ = data_;
                result.dataInfo_ = internalGetDataInfo();
                result.dataInfo_.makeImmutable();
                result.endFlag_ = endFlag_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof TtsResult) {
                    return mergeFrom((TtsResult) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(TtsResult other) {
                if (other == TtsResult.getDefaultInstance()) return this;
                if (!other.getErrStr().isEmpty()) {
                    errStr_ = other.errStr_;
                    onChanged();
                }
                if (other.getErrCode() != 0) {
                    setErrCode(other.getErrCode());
                }
                if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
                    setData(other.getData());
                }
                internalGetMutableDataInfo().mergeFrom(
                        other.internalGetDataInfo());
                if (other.getEndFlag() != false) {
                    setEndFlag(other.getEndFlag());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                TtsResult parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (TtsResult) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private Object errStr_ = "";

            /**
             * <pre>
             * 错误描述
             * </pre>
             *
             * <code>string errStr = 1;</code>
             */
            public String getErrStr() {
                Object ref = errStr_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    errStr_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <pre>
             * 错误描述
             * </pre>
             *
             * <code>string errStr = 1;</code>
             */
            public com.google.protobuf.ByteString
            getErrStrBytes() {
                Object ref = errStr_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    errStr_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 错误描述
             * </pre>
             *
             * <code>string errStr = 1;</code>
             */
            public Builder setErrStr(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                errStr_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 错误描述
             * </pre>
             *
             * <code>string errStr = 1;</code>
             */
            public Builder clearErrStr() {

                errStr_ = getDefaultInstance().getErrStr();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 错误描述
             * </pre>
             *
             * <code>string errStr = 1;</code>
             */
            public Builder setErrStrBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                errStr_ = value;
                onChanged();
                return this;
            }

            private int errCode_;

            /**
             * <pre>
             * 错误码
             * </pre>
             *
             * <code>int32 errCode = 2;</code>
             */
            public int getErrCode() {
                return errCode_;
            }

            /**
             * <pre>
             * 错误码
             * </pre>
             *
             * <code>int32 errCode = 2;</code>
             */
            public Builder setErrCode(int value) {

                errCode_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 错误码
             * </pre>
             *
             * <code>int32 errCode = 2;</code>
             */
            public Builder clearErrCode() {

                errCode_ = 0;
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <pre>
             * 返回的音频数据（没有音频头）
             * </pre>
             *
             * <code>bytes data = 3;</code>
             */
            public com.google.protobuf.ByteString getData() {
                return data_;
            }

            /**
             * <pre>
             * 返回的音频数据（没有音频头）
             * </pre>
             *
             * <code>bytes data = 3;</code>
             */
            public Builder setData(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                data_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 返回的音频数据（没有音频头）
             * </pre>
             *
             * <code>bytes data = 3;</code>
             */
            public Builder clearData() {

                data_ = getDefaultInstance().getData();
                onChanged();
                return this;
            }

            private com.google.protobuf.MapField<
                    String, String> dataInfo_;

            private com.google.protobuf.MapField<String, String>
            internalGetDataInfo() {
                if (dataInfo_ == null) {
                    return com.google.protobuf.MapField.emptyMapField(
                            DataInfoDefaultEntryHolder.defaultEntry);
                }
                return dataInfo_;
            }

            private com.google.protobuf.MapField<String, String>
            internalGetMutableDataInfo() {
                onChanged();
                ;
                if (dataInfo_ == null) {
                    dataInfo_ = com.google.protobuf.MapField.newMapField(
                            DataInfoDefaultEntryHolder.defaultEntry);
                }
                if (!dataInfo_.isMutable()) {
                    dataInfo_ = dataInfo_.copy();
                }
                return dataInfo_;
            }

            public int getDataInfoCount() {
                return internalGetDataInfo().getMap().size();
            }

            /**
             * <pre>
             * 音频数据的信息
             * </pre>
             *
             * <code>map&lt;string, string&gt; dataInfo = 4;</code>
             */

            public boolean containsDataInfo(
                    String key) {
                if (key == null) {
                    throw new NullPointerException();
                }
                return internalGetDataInfo().getMap().containsKey(key);
            }

            /**
             * Use {@link #getDataInfoMap()} instead.
             */
            @Deprecated
            public java.util.Map<String, String> getDataInfo() {
                return getDataInfoMap();
            }

            /**
             * <pre>
             * 音频数据的信息
             * </pre>
             *
             * <code>map&lt;string, string&gt; dataInfo = 4;</code>
             */

            public java.util.Map<String, String> getDataInfoMap() {
                return internalGetDataInfo().getMap();
            }

            /**
             * <pre>
             * 音频数据的信息
             * </pre>
             *
             * <code>map&lt;string, string&gt; dataInfo = 4;</code>
             */

            public String getDataInfoOrDefault(
                    String key,
                    String defaultValue) {
                if (key == null) {
                    throw new NullPointerException();
                }
                java.util.Map<String, String> map =
                        internalGetDataInfo().getMap();
                return map.containsKey(key) ? map.get(key) : defaultValue;
            }

            /**
             * <pre>
             * 音频数据的信息
             * </pre>
             *
             * <code>map&lt;string, string&gt; dataInfo = 4;</code>
             */

            public String getDataInfoOrThrow(
                    String key) {
                if (key == null) {
                    throw new NullPointerException();
                }
                java.util.Map<String, String> map =
                        internalGetDataInfo().getMap();
                if (!map.containsKey(key)) {
                    throw new IllegalArgumentException();
                }
                return map.get(key);
            }

            public Builder clearDataInfo() {
                internalGetMutableDataInfo().getMutableMap()
                        .clear();
                return this;
            }

            /**
             * <pre>
             * 音频数据的信息
             * </pre>
             *
             * <code>map&lt;string, string&gt; dataInfo = 4;</code>
             */

            public Builder removeDataInfo(
                    String key) {
                if (key == null) {
                    throw new NullPointerException();
                }
                internalGetMutableDataInfo().getMutableMap()
                        .remove(key);
                return this;
            }

            /**
             * Use alternate mutation accessors instead.
             */
            @Deprecated
            public java.util.Map<String, String>
            getMutableDataInfo() {
                return internalGetMutableDataInfo().getMutableMap();
            }

            /**
             * <pre>
             * 音频数据的信息
             * </pre>
             *
             * <code>map&lt;string, string&gt; dataInfo = 4;</code>
             */
            public Builder putDataInfo(
                    String key,
                    String value) {
                if (key == null) {
                    throw new NullPointerException();
                }
                if (value == null) {
                    throw new NullPointerException();
                }
                internalGetMutableDataInfo().getMutableMap()
                        .put(key, value);
                return this;
            }

            /**
             * <pre>
             * 音频数据的信息
             * </pre>
             *
             * <code>map&lt;string, string&gt; dataInfo = 4;</code>
             */

            public Builder putAllDataInfo(
                    java.util.Map<String, String> values) {
                internalGetMutableDataInfo().getMutableMap()
                        .putAll(values);
                return this;
            }

            private boolean endFlag_;

            /**
             * <pre>
             * 最后一次音频标识符
             * </pre>
             *
             * <code>bool endFlag = 5;</code>
             */
            public boolean getEndFlag() {
                return endFlag_;
            }

            /**
             * <pre>
             * 最后一次音频标识符
             * </pre>
             *
             * <code>bool endFlag = 5;</code>
             */
            public Builder setEndFlag(boolean value) {

                endFlag_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 最后一次音频标识符
             * </pre>
             *
             * <code>bool endFlag = 5;</code>
             */
            public Builder clearEndFlag() {

                endFlag_ = false;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:tts.TtsResult)
        }

        // @@protoc_insertion_point(class_scope:tts.TtsResult)
        private static final TtsResult DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new TtsResult();
        }

        public static TtsResult getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<TtsResult>
                PARSER = new com.google.protobuf.AbstractParser<TtsResult>() {
            public TtsResult parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new TtsResult(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<TtsResult> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<TtsResult> getParserForType() {
            return PARSER;
        }

        public TtsResult getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_tts_TtsRequest_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_tts_TtsRequest_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_tts_TtsRequest_SessionParamEntry_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_tts_TtsRequest_SessionParamEntry_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_tts_TtsResult_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_tts_TtsResult_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_tts_TtsResult_DataInfoEntry_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_tts_TtsResult_DataInfoEntry_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\tTts.proto\022\003tts\"\231\001\n\nTtsRequest\0227\n\014sessi" +
                        "onParam\030\001 \003(\0132!.tts.TtsRequest.SessionPa" +
                        "ramEntry\022\014\n\004text\030\002 \001(\t\022\017\n\007endFlag\030\003 \001(\010\032" +
                        "3\n\021SessionParamEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005val" +
                        "ue\030\002 \001(\t:\0028\001\"\254\001\n\tTtsResult\022\016\n\006errStr\030\001 \001" +
                        "(\t\022\017\n\007errCode\030\002 \001(\005\022\014\n\004data\030\003 \001(\014\022.\n\010dat" +
                        "aInfo\030\004 \003(\0132\034.tts.TtsResult.DataInfoEntr" +
                        "y\022\017\n\007endFlag\030\005 \001(\010\032/\n\rDataInfoEntry\022\013\n\003k" +
                        "ey\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\00129\n\003Tts\0222\n\tcr" +
                        "eateRec\022\017.tts.TtsRequest\032\016.tts.TtsResult",
                "\"\000(\0010\001B\032\n\030com.iflytek.tts.sdk.coreb\006prot" +
                        "o3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_tts_TtsRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_tts_TtsRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_tts_TtsRequest_descriptor,
                new String[]{"SessionParam", "Text", "EndFlag",});
        internal_static_tts_TtsRequest_SessionParamEntry_descriptor =
                internal_static_tts_TtsRequest_descriptor.getNestedTypes().get(0);
        internal_static_tts_TtsRequest_SessionParamEntry_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_tts_TtsRequest_SessionParamEntry_descriptor,
                new String[]{"Key", "Value",});
        internal_static_tts_TtsResult_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_tts_TtsResult_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_tts_TtsResult_descriptor,
                new String[]{"ErrStr", "ErrCode", "Data", "DataInfo", "EndFlag",});
        internal_static_tts_TtsResult_DataInfoEntry_descriptor =
                internal_static_tts_TtsResult_descriptor.getNestedTypes().get(0);
        internal_static_tts_TtsResult_DataInfoEntry_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_tts_TtsResult_DataInfoEntry_descriptor,
                new String[]{"Key", "Value",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
