// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tes.proto

package com.iflytek.tts.sdk.core;

public final class Tes {
    private Tes() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface TESRequestOrBuilder extends
            // @@protoc_insertion_point(interface_extends:tes.TESRequest)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * 请求的类型
         * </pre>
         *
         * <code>string type = 1;</code>
         */
        String getType();

        /**
         * <pre>
         * 请求的类型
         * </pre>
         *
         * <code>string type = 1;</code>
         */
        com.google.protobuf.ByteString
        getTypeBytes();

        /**
         * <pre>
         * 请求的参数
         * </pre>
         *
         * <code>string sParam = 2;</code>
         */
        String getSParam();

        /**
         * <pre>
         * 请求的参数
         * </pre>
         *
         * <code>string sParam = 2;</code>
         */
        com.google.protobuf.ByteString
        getSParamBytes();

        /**
         * <pre>
         * 请求的参数
         * </pre>
         *
         * <code>bytes bParam = 3;</code>
         */
        com.google.protobuf.ByteString getBParam();
    }

    /**
     * Protobuf type {@code tes.TESRequest}
     */
    public static final class TESRequest extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:tes.TESRequest)
            TESRequestOrBuilder {
        // Use TESRequest.newBuilder() to construct.
        private TESRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private TESRequest() {
            type_ = "";
            sParam_ = "";
            bParam_ = com.google.protobuf.ByteString.EMPTY;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private TESRequest(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            String s = input.readStringRequireUtf8();

                            type_ = s;
                            break;
                        }
                        case 18: {
                            String s = input.readStringRequireUtf8();

                            sParam_ = s;
                            break;
                        }
                        case 26: {

                            bParam_ = input.readBytes();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Tes.internal_static_tes_TESRequest_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Tes.internal_static_tes_TESRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            TESRequest.class, Builder.class);
        }

        public static final int TYPE_FIELD_NUMBER = 1;
        private volatile Object type_;

        /**
         * <pre>
         * 请求的类型
         * </pre>
         *
         * <code>string type = 1;</code>
         */
        public String getType() {
            Object ref = type_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                type_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 请求的类型
         * </pre>
         *
         * <code>string type = 1;</code>
         */
        public com.google.protobuf.ByteString
        getTypeBytes() {
            Object ref = type_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                type_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int SPARAM_FIELD_NUMBER = 2;
        private volatile Object sParam_;

        /**
         * <pre>
         * 请求的参数
         * </pre>
         *
         * <code>string sParam = 2;</code>
         */
        public String getSParam() {
            Object ref = sParam_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                sParam_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 请求的参数
         * </pre>
         *
         * <code>string sParam = 2;</code>
         */
        public com.google.protobuf.ByteString
        getSParamBytes() {
            Object ref = sParam_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                sParam_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int BPARAM_FIELD_NUMBER = 3;
        private com.google.protobuf.ByteString bParam_;

        /**
         * <pre>
         * 请求的参数
         * </pre>
         *
         * <code>bytes bParam = 3;</code>
         */
        public com.google.protobuf.ByteString getBParam() {
            return bParam_;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getTypeBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
            }
            if (!getSParamBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sParam_);
            }
            if (!bParam_.isEmpty()) {
                output.writeBytes(3, bParam_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getTypeBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
            }
            if (!getSParamBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sParam_);
            }
            if (!bParam_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(3, bParam_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof TESRequest)) {
                return super.equals(obj);
            }
            TESRequest other = (TESRequest) obj;

            boolean result = true;
            result = result && getType()
                    .equals(other.getType());
            result = result && getSParam()
                    .equals(other.getSParam());
            result = result && getBParam()
                    .equals(other.getBParam());
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + TYPE_FIELD_NUMBER;
            hash = (53 * hash) + getType().hashCode();
            hash = (37 * hash) + SPARAM_FIELD_NUMBER;
            hash = (53 * hash) + getSParam().hashCode();
            hash = (37 * hash) + BPARAM_FIELD_NUMBER;
            hash = (53 * hash) + getBParam().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static TESRequest parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static TESRequest parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TESRequest parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static TESRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TESRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static TESRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TESRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static TESRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static TESRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static TESRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static TESRequest parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static TESRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(TESRequest prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code tes.TESRequest}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:tes.TESRequest)
                TESRequestOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Tes.internal_static_tes_TESRequest_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Tes.internal_static_tes_TESRequest_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                TESRequest.class, Builder.class);
            }

            // Construct using com.iflytek.tts.sdk.core.Tes.TESRequest.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                type_ = "";

                sParam_ = "";

                bParam_ = com.google.protobuf.ByteString.EMPTY;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Tes.internal_static_tes_TESRequest_descriptor;
            }

            public TESRequest getDefaultInstanceForType() {
                return TESRequest.getDefaultInstance();
            }

            public TESRequest build() {
                TESRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public TESRequest buildPartial() {
                TESRequest result = new TESRequest(this);
                result.type_ = type_;
                result.sParam_ = sParam_;
                result.bParam_ = bParam_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof TESRequest) {
                    return mergeFrom((TESRequest) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(TESRequest other) {
                if (other == TESRequest.getDefaultInstance()) return this;
                if (!other.getType().isEmpty()) {
                    type_ = other.type_;
                    onChanged();
                }
                if (!other.getSParam().isEmpty()) {
                    sParam_ = other.sParam_;
                    onChanged();
                }
                if (other.getBParam() != com.google.protobuf.ByteString.EMPTY) {
                    setBParam(other.getBParam());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                TESRequest parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (TESRequest) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private Object type_ = "";

            /**
             * <pre>
             * 请求的类型
             * </pre>
             *
             * <code>string type = 1;</code>
             */
            public String getType() {
                Object ref = type_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    type_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <pre>
             * 请求的类型
             * </pre>
             *
             * <code>string type = 1;</code>
             */
            public com.google.protobuf.ByteString
            getTypeBytes() {
                Object ref = type_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    type_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 请求的类型
             * </pre>
             *
             * <code>string type = 1;</code>
             */
            public Builder setType(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                type_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 请求的类型
             * </pre>
             *
             * <code>string type = 1;</code>
             */
            public Builder clearType() {

                type_ = getDefaultInstance().getType();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 请求的类型
             * </pre>
             *
             * <code>string type = 1;</code>
             */
            public Builder setTypeBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                type_ = value;
                onChanged();
                return this;
            }

            private Object sParam_ = "";

            /**
             * <pre>
             * 请求的参数
             * </pre>
             *
             * <code>string sParam = 2;</code>
             */
            public String getSParam() {
                Object ref = sParam_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    sParam_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <pre>
             * 请求的参数
             * </pre>
             *
             * <code>string sParam = 2;</code>
             */
            public com.google.protobuf.ByteString
            getSParamBytes() {
                Object ref = sParam_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    sParam_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 请求的参数
             * </pre>
             *
             * <code>string sParam = 2;</code>
             */
            public Builder setSParam(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                sParam_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 请求的参数
             * </pre>
             *
             * <code>string sParam = 2;</code>
             */
            public Builder clearSParam() {

                sParam_ = getDefaultInstance().getSParam();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 请求的参数
             * </pre>
             *
             * <code>string sParam = 2;</code>
             */
            public Builder setSParamBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                sParam_ = value;
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString bParam_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <pre>
             * 请求的参数
             * </pre>
             *
             * <code>bytes bParam = 3;</code>
             */
            public com.google.protobuf.ByteString getBParam() {
                return bParam_;
            }

            /**
             * <pre>
             * 请求的参数
             * </pre>
             *
             * <code>bytes bParam = 3;</code>
             */
            public Builder setBParam(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                bParam_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 请求的参数
             * </pre>
             *
             * <code>bytes bParam = 3;</code>
             */
            public Builder clearBParam() {

                bParam_ = getDefaultInstance().getBParam();
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:tes.TESRequest)
        }

        // @@protoc_insertion_point(class_scope:tes.TESRequest)
        private static final TESRequest DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new TESRequest();
        }

        public static TESRequest getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<TESRequest>
                PARSER = new com.google.protobuf.AbstractParser<TESRequest>() {
            public TESRequest parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new TESRequest(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<TESRequest> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<TESRequest> getParserForType() {
            return PARSER;
        }

        public TESRequest getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface TESResultOrBuilder extends
            // @@protoc_insertion_point(interface_extends:tes.TESResult)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * 返回的错误信息
         * </pre>
         *
         * <code>string errStr = 1;</code>
         */
        String getErrStr();

        /**
         * <pre>
         * 返回的错误信息
         * </pre>
         *
         * <code>string errStr = 1;</code>
         */
        com.google.protobuf.ByteString
        getErrStrBytes();

        /**
         * <pre>
         * 返回的错误码
         * </pre>
         *
         * <code>int32 errCode = 2;</code>
         */
        int getErrCode();

        /**
         * <pre>
         * 返回的结果
         * </pre>
         *
         * <code>string sResult = 3;</code>
         */
        String getSResult();

        /**
         * <pre>
         * 返回的结果
         * </pre>
         *
         * <code>string sResult = 3;</code>
         */
        com.google.protobuf.ByteString
        getSResultBytes();

        /**
         * <pre>
         * 返回的结果
         * </pre>
         *
         * <code>bytes bResult = 4;</code>
         */
        com.google.protobuf.ByteString getBResult();
    }

    /**
     * Protobuf type {@code tes.TESResult}
     */
    public static final class TESResult extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:tes.TESResult)
            TESResultOrBuilder {
        // Use TESResult.newBuilder() to construct.
        private TESResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private TESResult() {
            errStr_ = "";
            errCode_ = 0;
            sResult_ = "";
            bResult_ = com.google.protobuf.ByteString.EMPTY;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private TESResult(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            String s = input.readStringRequireUtf8();

                            errStr_ = s;
                            break;
                        }
                        case 16: {

                            errCode_ = input.readInt32();
                            break;
                        }
                        case 26: {
                            String s = input.readStringRequireUtf8();

                            sResult_ = s;
                            break;
                        }
                        case 34: {

                            bResult_ = input.readBytes();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Tes.internal_static_tes_TESResult_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Tes.internal_static_tes_TESResult_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            TESResult.class, Builder.class);
        }

        public static final int ERRSTR_FIELD_NUMBER = 1;
        private volatile Object errStr_;

        /**
         * <pre>
         * 返回的错误信息
         * </pre>
         *
         * <code>string errStr = 1;</code>
         */
        public String getErrStr() {
            Object ref = errStr_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                errStr_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 返回的错误信息
         * </pre>
         *
         * <code>string errStr = 1;</code>
         */
        public com.google.protobuf.ByteString
        getErrStrBytes() {
            Object ref = errStr_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                errStr_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int ERRCODE_FIELD_NUMBER = 2;
        private int errCode_;

        /**
         * <pre>
         * 返回的错误码
         * </pre>
         *
         * <code>int32 errCode = 2;</code>
         */
        public int getErrCode() {
            return errCode_;
        }

        public static final int SRESULT_FIELD_NUMBER = 3;
        private volatile Object sResult_;

        /**
         * <pre>
         * 返回的结果
         * </pre>
         *
         * <code>string sResult = 3;</code>
         */
        public String getSResult() {
            Object ref = sResult_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                sResult_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 返回的结果
         * </pre>
         *
         * <code>string sResult = 3;</code>
         */
        public com.google.protobuf.ByteString
        getSResultBytes() {
            Object ref = sResult_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                sResult_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int BRESULT_FIELD_NUMBER = 4;
        private com.google.protobuf.ByteString bResult_;

        /**
         * <pre>
         * 返回的结果
         * </pre>
         *
         * <code>bytes bResult = 4;</code>
         */
        public com.google.protobuf.ByteString getBResult() {
            return bResult_;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getErrStrBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, errStr_);
            }
            if (errCode_ != 0) {
                output.writeInt32(2, errCode_);
            }
            if (!getSResultBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sResult_);
            }
            if (!bResult_.isEmpty()) {
                output.writeBytes(4, bResult_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getErrStrBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, errStr_);
            }
            if (errCode_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, errCode_);
            }
            if (!getSResultBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sResult_);
            }
            if (!bResult_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(4, bResult_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof TESResult)) {
                return super.equals(obj);
            }
            TESResult other = (TESResult) obj;

            boolean result = true;
            result = result && getErrStr()
                    .equals(other.getErrStr());
            result = result && (getErrCode()
                    == other.getErrCode());
            result = result && getSResult()
                    .equals(other.getSResult());
            result = result && getBResult()
                    .equals(other.getBResult());
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + ERRSTR_FIELD_NUMBER;
            hash = (53 * hash) + getErrStr().hashCode();
            hash = (37 * hash) + ERRCODE_FIELD_NUMBER;
            hash = (53 * hash) + getErrCode();
            hash = (37 * hash) + SRESULT_FIELD_NUMBER;
            hash = (53 * hash) + getSResult().hashCode();
            hash = (37 * hash) + BRESULT_FIELD_NUMBER;
            hash = (53 * hash) + getBResult().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static TESResult parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static TESResult parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TESResult parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static TESResult parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TESResult parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static TESResult parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TESResult parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static TESResult parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static TESResult parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static TESResult parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static TESResult parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static TESResult parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(TESResult prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code tes.TESResult}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:tes.TESResult)
                TESResultOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Tes.internal_static_tes_TESResult_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Tes.internal_static_tes_TESResult_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                TESResult.class, Builder.class);
            }

            // Construct using com.iflytek.tts.sdk.core.Tes.TESResult.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                errStr_ = "";

                errCode_ = 0;

                sResult_ = "";

                bResult_ = com.google.protobuf.ByteString.EMPTY;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Tes.internal_static_tes_TESResult_descriptor;
            }

            public TESResult getDefaultInstanceForType() {
                return TESResult.getDefaultInstance();
            }

            public TESResult build() {
                TESResult result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public TESResult buildPartial() {
                TESResult result = new TESResult(this);
                result.errStr_ = errStr_;
                result.errCode_ = errCode_;
                result.sResult_ = sResult_;
                result.bResult_ = bResult_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof TESResult) {
                    return mergeFrom((TESResult) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(TESResult other) {
                if (other == TESResult.getDefaultInstance()) return this;
                if (!other.getErrStr().isEmpty()) {
                    errStr_ = other.errStr_;
                    onChanged();
                }
                if (other.getErrCode() != 0) {
                    setErrCode(other.getErrCode());
                }
                if (!other.getSResult().isEmpty()) {
                    sResult_ = other.sResult_;
                    onChanged();
                }
                if (other.getBResult() != com.google.protobuf.ByteString.EMPTY) {
                    setBResult(other.getBResult());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                TESResult parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (TESResult) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private Object errStr_ = "";

            /**
             * <pre>
             * 返回的错误信息
             * </pre>
             *
             * <code>string errStr = 1;</code>
             */
            public String getErrStr() {
                Object ref = errStr_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    errStr_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <pre>
             * 返回的错误信息
             * </pre>
             *
             * <code>string errStr = 1;</code>
             */
            public com.google.protobuf.ByteString
            getErrStrBytes() {
                Object ref = errStr_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    errStr_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 返回的错误信息
             * </pre>
             *
             * <code>string errStr = 1;</code>
             */
            public Builder setErrStr(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                errStr_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 返回的错误信息
             * </pre>
             *
             * <code>string errStr = 1;</code>
             */
            public Builder clearErrStr() {

                errStr_ = getDefaultInstance().getErrStr();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 返回的错误信息
             * </pre>
             *
             * <code>string errStr = 1;</code>
             */
            public Builder setErrStrBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                errStr_ = value;
                onChanged();
                return this;
            }

            private int errCode_;

            /**
             * <pre>
             * 返回的错误码
             * </pre>
             *
             * <code>int32 errCode = 2;</code>
             */
            public int getErrCode() {
                return errCode_;
            }

            /**
             * <pre>
             * 返回的错误码
             * </pre>
             *
             * <code>int32 errCode = 2;</code>
             */
            public Builder setErrCode(int value) {

                errCode_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 返回的错误码
             * </pre>
             *
             * <code>int32 errCode = 2;</code>
             */
            public Builder clearErrCode() {

                errCode_ = 0;
                onChanged();
                return this;
            }

            private Object sResult_ = "";

            /**
             * <pre>
             * 返回的结果
             * </pre>
             *
             * <code>string sResult = 3;</code>
             */
            public String getSResult() {
                Object ref = sResult_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    sResult_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <pre>
             * 返回的结果
             * </pre>
             *
             * <code>string sResult = 3;</code>
             */
            public com.google.protobuf.ByteString
            getSResultBytes() {
                Object ref = sResult_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    sResult_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 返回的结果
             * </pre>
             *
             * <code>string sResult = 3;</code>
             */
            public Builder setSResult(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                sResult_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 返回的结果
             * </pre>
             *
             * <code>string sResult = 3;</code>
             */
            public Builder clearSResult() {

                sResult_ = getDefaultInstance().getSResult();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 返回的结果
             * </pre>
             *
             * <code>string sResult = 3;</code>
             */
            public Builder setSResultBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                sResult_ = value;
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString bResult_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <pre>
             * 返回的结果
             * </pre>
             *
             * <code>bytes bResult = 4;</code>
             */
            public com.google.protobuf.ByteString getBResult() {
                return bResult_;
            }

            /**
             * <pre>
             * 返回的结果
             * </pre>
             *
             * <code>bytes bResult = 4;</code>
             */
            public Builder setBResult(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                bResult_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 返回的结果
             * </pre>
             *
             * <code>bytes bResult = 4;</code>
             */
            public Builder clearBResult() {

                bResult_ = getDefaultInstance().getBResult();
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:tes.TESResult)
        }

        // @@protoc_insertion_point(class_scope:tes.TESResult)
        private static final TESResult DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new TESResult();
        }

        public static TESResult getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<TESResult>
                PARSER = new com.google.protobuf.AbstractParser<TESResult>() {
            public TESResult parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new TESResult(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<TESResult> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<TESResult> getParserForType() {
            return PARSER;
        }

        public TESResult getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_tes_TESRequest_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_tes_TESRequest_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_tes_TESResult_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_tes_TESResult_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\ttes.proto\022\003tes\":\n\nTESRequest\022\014\n\004type\030\001" +
                        " \001(\t\022\016\n\006sParam\030\002 \001(\t\022\016\n\006bParam\030\003 \001(\014\"N\n\t" +
                        "TESResult\022\016\n\006errStr\030\001 \001(\t\022\017\n\007errCode\030\002 \001" +
                        "(\005\022\017\n\007sResult\030\003 \001(\t\022\017\n\007bResult\030\004 \001(\01424\n\003" +
                        "TES\022-\n\010OnNotify\022\017.tes.TESRequest\032\016.tes.T" +
                        "ESResult\"\000B\032\n\030com.iflytek.tts.sdk.coreb\006" +
                        "proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_tes_TESRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_tes_TESRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_tes_TESRequest_descriptor,
                new String[]{"Type", "SParam", "BParam",});
        internal_static_tes_TESResult_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_tes_TESResult_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_tes_TESResult_descriptor,
                new String[]{"ErrStr", "ErrCode", "SResult", "BResult",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
